import type { Product } from '../types'

export const seedProducts: Product[] = [
  {
    id: 1,
    slug: 'futbolka-tr',
    sku: 'TR-01',
    name: 'Футболка TR',
    collection: 'TR',
    description: 'Широкий рукав, свободный силуэт, тональный знак TR.',
    price: 6900,
    colors: ['Чёрный', 'Белый'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: true,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'tl',
  },
  {
    id: 2,
    slug: 'longsliv-tr',
    sku: 'TR-02',
    name: 'Лонгслив TR',
    collection: 'TR',
    description: 'Удлинённый прямой рукав без манжеты, знак TR у сердца.',
    price: 7900,
    colors: ['Чёрный', 'Белый'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: true,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'tr',
  },
  {
    id: 3,
    slug: 'futbolka-ugol',
    sku: 'TR-03',
    name: 'Футболка «Угол»',
    collection: 'УГОЛ',
    description: 'Оверсайз-футболка с графическим принтом коллекции «Угол».',
    price: 7500,
    colors: ['Чёрный'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: true,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'br',
  },
  {
    id: 4,
    slug: 'longsliv-ugol',
    sku: 'TR-04',
    name: 'Лонгслив «Угол»',
    collection: 'УГОЛ',
    description: 'Свободный лонгслив с угловой графикой и прямым рукавом.',
    price: 8500,
    colors: ['Графит'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: true,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'br',
  },
  {
    id: 5,
    slug: 'futbolka-kapkan',
    sku: 'TR-05',
    name: 'Футболка «Капкан»',
    collection: 'КАПКАН',
    description: 'Прямоугольный графический принт, плотный хлопок, оверсайз.',
    price: 7900,
    colors: ['Чёрный'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: false,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'bl',
  },
  {
    id: 6,
    slug: 'longsliv-kapkan',
    sku: 'TR-06',
    name: 'Лонгслив «Капкан»',
    collection: 'КАПКАН',
    description: 'Удлинённый лонгслив с монохромной графикой.',
    price: 8900,
    colors: ['Чёрный', 'Серый'],
    sizes: ['M–L', 'XL–XXL'],
    stock: 4,
    status: 'active',
    featured: false,
    composition: 'Плотный хлопок. Финальный состав уточняется перед запуском.',
    fit: 'Свободная, унисекс. Размерная сетка M–L и XL–XXL.',
    sprite: 'bl',
  },
]
